name: nmap

on: 
  workflow_dispatch:
    inputs:
      pincode:
        description: 'IP ADDRESS'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: sudo apt install nmap -y && whoami
      
    - name: nmap
      run: nmap {{ github.event.inputs.pincode }}
